package webserver.server;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by 4P on 2017/7/2.
 */
public class HttpParam {
    //Http Version
    public static final String HTTP_VERSION = "HTTP/1.1";

    //Request Method
    public static final int METHOD_GET = 0;
    public static final int METHOD_POST = 1;
    public static final int METHOD_HEAD = 2;

    //Response Status
    public static final int RESPONSE_OK = 200;
    public static final int RESPONSE_NOT_FOUND = 404;
    public static final int RESPONSE_INTERNAL_SERVER_ERROR = 500;
    public static final int RESPONSE_METHOD_NOT_IMPLEMENT = 501;

    public static Map<String, String> MIMEMAP;
    public static Map<String, String> STATUSMAP;

    public static void initMimeMap(){
        MIMEMAP = new HashMap<String, String>();
        MIMEMAP.put("abs","audio/x-mpeg");
        MIMEMAP.put("ai","application/postscript");
        MIMEMAP.put("aif","audio/x-aiff");
        MIMEMAP.put("aifc","audio/x-aiff");
        MIMEMAP.put("aiff","audio/x-aiff");
        MIMEMAP.put("aim","application/x-aim");
        MIMEMAP.put("art","image/x-jg");
        MIMEMAP.put("asf","video/x-ms-asf");
        MIMEMAP.put("asx","video/x-ms-asf");
        MIMEMAP.put("au","audio/basic");
        MIMEMAP.put("avi","video/x-msvideo");
        MIMEMAP.put("avx","video/x-rad-screenplay");
        MIMEMAP.put("bcpio","application/x-bcpio");
        MIMEMAP.put("bin","application/octet-stream");
        MIMEMAP.put("bmp","image/bmp");
        MIMEMAP.put("body","text/html");
        MIMEMAP.put("cdf","application/x-netcdf");
        MIMEMAP.put("cer","application/x-x509-ca-cert");
        MIMEMAP.put("class","application/java");
        MIMEMAP.put("cpio","application/x-cpio");
        MIMEMAP.put("csh","application/x-csh");
        MIMEMAP.put("css","text/css");
        MIMEMAP.put("dib","image/bmp");
        MIMEMAP.put("doc","application/msword");
        MIMEMAP.put("dtd","application/xml-dtd");
        MIMEMAP.put("dv","video/x-dv");
        MIMEMAP.put("dvi","application/x-dvi");
        MIMEMAP.put("eps","application/postscript");
        MIMEMAP.put("etx","text/x-setext");
        MIMEMAP.put("exe","application/octet-stream");
        MIMEMAP.put("gif","image/gif");
        MIMEMAP.put("gtar","application/x-gtar");
        MIMEMAP.put("gz","application/x-gzip");
        MIMEMAP.put("hdf","application/x-hdf");
        MIMEMAP.put("htc","text/x-component");
        MIMEMAP.put("htm","text/html");
        MIMEMAP.put("html","text/html");
        MIMEMAP.put("hqx","application/mac-binhex40");
        MIMEMAP.put("ico","image/x-icon");
        MIMEMAP.put("ief","image/ief");
        MIMEMAP.put("jad","text/vnd.sun.j2me.app-descriptor");
        MIMEMAP.put("jar","application/java-archive");
        MIMEMAP.put("java","text/plain");
        MIMEMAP.put("jnlp","application/x-java-jnlp-file");
        MIMEMAP.put("jpe","image/jpeg");
        MIMEMAP.put("jpeg","image/jpeg");
        MIMEMAP.put("jpg","image/jpeg");
        MIMEMAP.put("js","text/javascript");
        MIMEMAP.put("jsf","text/plain");
        MIMEMAP.put("jspf","text/plain");
        MIMEMAP.put("kar","audio/midi");
        MIMEMAP.put("latex","application/x-latex");
        MIMEMAP.put("m3u","audio/x-mpegurl");
        MIMEMAP.put("mac","image/x-macpaint");
        MIMEMAP.put("man","application/x-troff-man");
        MIMEMAP.put("mathml","application/mathml+xml");
        MIMEMAP.put("me","application/x-troff-me");
        MIMEMAP.put("mid","audio/midi");
        MIMEMAP.put("midi","audio/midi");
        MIMEMAP.put("mif","application/vnd.mif");
        MIMEMAP.put("mov","video/quicktime");
        MIMEMAP.put("movie","video/x-sgi-movie");
        MIMEMAP.put("mp1","audio/x-mpeg");
        MIMEMAP.put("mp2","audio/mpeg");
        MIMEMAP.put("mp3","audio/mpeg");
        MIMEMAP.put("mp4","video/mp4");
        MIMEMAP.put("mpa","audio/x-mpeg");
        MIMEMAP.put("mpe","video/mpeg");
        MIMEMAP.put("mpeg","video/mpeg");
        MIMEMAP.put("mpega","audio/x-mpeg");
        MIMEMAP.put("mpg","video/mpeg");
        MIMEMAP.put("mpv2","video/mpeg2");
        MIMEMAP.put("ms","application/x-troff-ms");
        MIMEMAP.put("nc","application/x-netcdf");
        MIMEMAP.put("oda","application/oda");
        MIMEMAP.put("odb","application/vnd.oasis.opendocument.database");
        MIMEMAP.put("odc","application/vnd.oasis.opendocument.chart");
        MIMEMAP.put("odf","application/vnd.oasis.opendocument.formula");
        MIMEMAP.put("odg","application/vnd.oasis.opendocument.graphics");
        MIMEMAP.put("odi","application/vnd.oasis.opendocument.image");
        MIMEMAP.put("odm","application/vnd.oasis.opendocument.text-master");
        MIMEMAP.put("odp","application/vnd.oasis.opendocument.presentation");
        MIMEMAP.put("ods","application/vnd.oasis.opendocument.spreadsheet");
        MIMEMAP.put("odt","application/vnd.oasis.opendocument.text");
        MIMEMAP.put("ogg","application/ogg");
        MIMEMAP.put("otg ","application/vnd.oasis.opendocument.graphics-template");
        MIMEMAP.put("oth","application/vnd.oasis.opendocument.text-web");
        MIMEMAP.put("otp","application/vnd.oasis.opendocument.presentation-template");
        MIMEMAP.put("ots","application/vnd.oasis.opendocument.spreadsheet-template ");
        MIMEMAP.put("ott","application/vnd.oasis.opendocument.text-template");
        MIMEMAP.put("pbm","image/x-portable-bitmap");
        MIMEMAP.put("pct","image/pict");
        MIMEMAP.put("pdf","application/pdf");
        MIMEMAP.put("pgm","image/x-portable-graymap");
        MIMEMAP.put("pic","image/pict");
        MIMEMAP.put("pict","image/pict");
        MIMEMAP.put("pls","audio/x-scpls");
        MIMEMAP.put("png","image/png");
        MIMEMAP.put("pnm","image/x-portable-anymap");
        MIMEMAP.put("pnt","image/x-macpaint");
        MIMEMAP.put("ppm","image/x-portable-pixmap");
        MIMEMAP.put("pps","application/vnd.ms-powerpoint");
        MIMEMAP.put("ppt","application/vnd.ms-powerpoint");
        MIMEMAP.put("ps","application/postscript");
        MIMEMAP.put("psd","image/x-photoshop");
        MIMEMAP.put("qt","video/quicktime");
        MIMEMAP.put("qti","image/x-quicktime");
        MIMEMAP.put("qtif","image/x-quicktime");
        MIMEMAP.put("ras","image/x-cmu-raster");
        MIMEMAP.put("rdf","application/rdf+xml");
        MIMEMAP.put("rgb","image/x-rgb");
        MIMEMAP.put("rm","application/vnd.rn-realmedia");
        MIMEMAP.put("roff","application/x-troff");
        MIMEMAP.put("rtf","text/rtf");
        MIMEMAP.put("rtx","text/richtext");
        MIMEMAP.put("sh","application/x-sh");
        MIMEMAP.put("shar","application/x-shar");
        MIMEMAP.put("smf","audio/x-midi");
        MIMEMAP.put("sit","application/x-stuffit");
        MIMEMAP.put("snd","audio/basic");
        MIMEMAP.put("src","application/x-wais-source");
        MIMEMAP.put("sv4cpio","application/x-sv4cpio");
        MIMEMAP.put("sv4crc","application/x-sv4crc");
        MIMEMAP.put("svg","image/svg+xml");
        MIMEMAP.put("svgz","image/svg+xml");
        MIMEMAP.put("swf","application/x-shockwave-flash");
        MIMEMAP.put("t","application/x-troff");
        MIMEMAP.put("tar","application/x-tar");
        MIMEMAP.put("tcl","application/x-tcl");
        MIMEMAP.put("tex","application/x-tex");
        MIMEMAP.put("texi","application/x-texinfo");
        MIMEMAP.put("texinfo","application/x-texinfo");
        MIMEMAP.put("tif","image/tiff");
        MIMEMAP.put("tiff","image/tiff");
        MIMEMAP.put("tr","application/x-troff");
        MIMEMAP.put("tsv","text/tab-separated-values");
        MIMEMAP.put("txt","text/plain");
        MIMEMAP.put("ulw","audio/basic");
        MIMEMAP.put("ustar","application/x-ustar");
        MIMEMAP.put("vrml","model/vrml");
        MIMEMAP.put("vsd","application/x-visio");
        MIMEMAP.put("vxml","application/voicexml+xml");
        MIMEMAP.put("wav","audio/x-wav");
        MIMEMAP.put("wbmp","image/vnd.wap.wbmp");
        MIMEMAP.put("wml","text/vnd.wap.wml");
        MIMEMAP.put("wmlc","application/vnd.wap.wmlc");
        MIMEMAP.put("wmls","text/vnd.wap.wmlscript");
        MIMEMAP.put("wmlscriptc","application/vnd.wap.wmlscriptc");
        MIMEMAP.put("wmv","video/x-ms-wmv");
        MIMEMAP.put("wrl","model/vrml");
        MIMEMAP.put("xbm","image/x-xbitmap");
        MIMEMAP.put("xht","application/xhtml+xml");
        MIMEMAP.put("xhtml","application/xhtml+xml");
        MIMEMAP.put("xls","application/vnd.ms-excel");
        MIMEMAP.put("xml","application/xml");
        MIMEMAP.put("xpm","image/x-xpixmap");
        MIMEMAP.put("xsl","application/xml");
        MIMEMAP.put("xslt","application/xslt+xml");
        MIMEMAP.put("xul","application/vnd.mozilla.xul+xml");
        MIMEMAP.put("xwd","image/x-xwindowdump");
        MIMEMAP.put("Z","application/x-compress");
        MIMEMAP.put("z","application/x-compress");
        MIMEMAP.put("zip","application/zip");

    }

    public static void initStatusMap(){
        STATUSMAP = new HashMap<String,String>();
        STATUSMAP.put("100","Continue");
        STATUSMAP.put("101","Switching Protocols");
        STATUSMAP.put("200","OK");
        STATUSMAP.put("201","Created");
        STATUSMAP.put("202","Accepted");
        STATUSMAP.put("203","Non-authoritative Information");
        STATUSMAP.put("204","No Content");
        STATUSMAP.put("205","Reset Content");
        STATUSMAP.put("206","Partial Content");
        STATUSMAP.put("300","Multiple Choices");
        STATUSMAP.put("301","Moved Permanently");
        STATUSMAP.put("302","Found");
        STATUSMAP.put("303","See Other");
        STATUSMAP.put("304","Not Modified");
        STATUSMAP.put("305","Use Proxy");
        STATUSMAP.put("306 ","Unused");
        STATUSMAP.put("307","Temporary Redirect");
        STATUSMAP.put("400","Bad Request");
        STATUSMAP.put("401","Unauthorized");
        STATUSMAP.put("402","Payment Required");
        STATUSMAP.put("403","Forbidden");
        STATUSMAP.put("404","Not Found");
        STATUSMAP.put("405","Method Not Allowed");
        STATUSMAP.put("406","Not Acceptable");
        STATUSMAP.put("407","Proxy Authentication Required");
        STATUSMAP.put("408","Request Timeout");
        STATUSMAP.put("409","Conflict");
        STATUSMAP.put("410","Gone");
        STATUSMAP.put("411","Length Required");
        STATUSMAP.put("412","Precondition Failed");
        STATUSMAP.put("413","Request Entity Too Large");
        STATUSMAP.put("414","Request-url Too Long");
        STATUSMAP.put("415","Unsupported Media Type");
        STATUSMAP.put("416 ","");
        STATUSMAP.put("417","Expectation Failed");
        STATUSMAP.put("500 ","Internal Server Error");
        STATUSMAP.put("501","Not Implemented");
        STATUSMAP.put("502","Bad Gateway");
        STATUSMAP.put("503","Service Unavailable");
        STATUSMAP.put("504","Gateway Timeout");
        STATUSMAP.put("505","HTTP Version Not Supported");
    }
}
